import numpy as np
import pybullet as p
from scipy.spatial.transform import Rotation

TCP_OFFSET = [0, 0, 200, 0, 0, 0]  # mm/deg — must match ufactory_sim

_URDF_PATH = '/tmp/urdf/XI130506F56A19-with-tcp.urdf'  # generated by pyroki on startup

def set_pybullet(urdf_path=None, gui=False, camera_distance=1.5, camera_yaw=45, camera_pitch=-30, camera_target=(0, 0, 0.5)):
    import pybullet as p
    if urdf_path is None:
        urdf_path = _URDF_PATH

    client = p.connect(p.GUI if gui else p.DIRECT)
    if gui:
        p.resetDebugVisualizerCamera(
            cameraDistance=camera_distance,
            cameraYaw=camera_yaw,
            cameraPitch=camera_pitch,
            cameraTargetPosition=camera_target,
            physicsClientId=client,
        )
    robot_id = p.loadURDF(urdf_path, useFixedBase=True, physicsClientId=client)

    joint_indices = []
    eef_link_index = None
    for i in range(p.getNumJoints(robot_id, physicsClientId=client)):
        info = p.getJointInfo(robot_id, i, physicsClientId=client)
        link_name = info[12].decode('utf-8').lower()
        if info[2] != p.JOINT_FIXED:
            joint_indices.append(i)
        if any(k in link_name for k in ('tcp', 'eef', 'tool')):
            eef_link_index = i

    if eef_link_index is None:
        eef_link_index = p.getNumJoints(robot_id, physicsClientId=client) - 1

    num_links = p.getNumJoints(robot_id, physicsClientId=client)

    return {
        'client': client,
        'robot_id': robot_id,
        'joint_indices': joint_indices[:6],
        'eef_link': eef_link_index,
        'num_links': num_links,
        'gui': gui,
    }

def set_camera(arm, distance=1.5, yaw=45, pitch=-30, target=(0, 0, 0.5)):
    p.resetDebugVisualizerCamera(
        cameraDistance=distance,
        cameraYaw=yaw,
        cameraPitch=pitch,
        cameraTargetPosition=target,
        physicsClientId=arm['client'],
    )

def clear_errors(arm):
    pass  # no-op: pybullet has no error state to clear

def _highlight_self_collisions(arm):
    client, robot_id = arm['client'], arm['robot_id']
    p.performCollisionDetection(physicsClientId=client)
    contacts = p.getContactPoints(robot_id, robot_id, physicsClientId=client)
    colliding = set()
    if contacts:
        for c in contacts:
            colliding.add(c[3])  # linkIndexA (-1 = base)
            colliding.add(c[4])  # linkIndexB
    for link_idx in range(-1, arm['num_links']):
        color = [1, 0, 0, 1] if link_idx in colliding else [0.7, 0.7, 0.7, 1]
        p.changeVisualShape(robot_id, link_idx, rgbaColor=color, physicsClientId=client)

def set_joint_angles(arm, angles_deg):
    """
    set the joint angles of the simulated robot and return the resulting end-effector pose
    angles_deg: list of 6 joint angles in degrees
    returns: (error_code, [x_mm, y_mm, z_mm, rx_deg, ry_deg, rz_deg])
    """
    client, robot_id = arm['client'], arm['robot_id']
    for joint_idx, angle_rad in zip(arm['joint_indices'], np.deg2rad(angles_deg)):
        p.resetJointState(robot_id, joint_idx, float(angle_rad), physicsClientId=client)

    if arm['gui']:
        _highlight_self_collisions(arm)

    state = p.getLinkState(robot_id, arm['eef_link'],
                           computeForwardKinematics=True, physicsClientId=client)
    pos_mm = np.array(state[4]) * 1000.0          # meters → mm
    orn_deg = _quat_to_rotvec_deg(state[5])        # quaternion → rotvec deg
    return 0, list(pos_mm) + list(orn_deg)

def get_joint_angles(arm, is_radian=False):
    angles = np.array([
        p.getJointState(arm['robot_id'], j, physicsClientId=arm['client'])[0]
        for j in arm['joint_indices']
    ])
    return angles if is_radian else np.rad2deg(angles)

def _quat_to_rotvec_deg(q_xyzw):
    rotvec_rad = Rotation.from_quat(q_xyzw).as_rotvec()
    return np.rad2deg(rotvec_rad)
